language: node_js
node_js:
  - stable

script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: "Lvy3YYCMdZZf2xfdVljUgB1ty2KeaYp+rd0MX7+6eXRJkXHiy4GuJxq1uRRAWW9BWPs39MZcVr1PkQDOs7ghn+m/p8SUdY5BEosKiH21R6phXWSokPV4YJwBUhWNTFkiXD7ZMBDCAAW5Rd6Wminq8qvrwwz10cwGOoZiaMW/Ojovf7T5XR8FpCCEbghIf/WMloQsA28X+G2DkCw3+EXcjNNOHfKVSv3X/G2RCznlcUzUhYJ4oHNMC8BzRNHsahm8UkffYjSo3DYsmqzNeEvOJhBWTxK4bYfPjG6m5ocSoaXDbSQnAEr45gFCfkW0k+9xS8M7ynHshDsY+03e0stq3Aiu9AmpkhwQnXn3P+9aqtGnD1QUWwcQ3rXwBVEn2FUBibHbVA+W4DhRl7DbVzpur3JAfKKCbJWAKY53Pd7/QSIPLicO5vmYVM1j/V9L565F/+6dfs8EjQ3LtUx/7hgb5BNAvpXV8u7T/FJJ1jN5OXNqdhoXEHACictXRiXLH3o4Wy4soFwajDTue1N5SQI58iTWNGx/V+Fim6tdYVOpMKCb7Q+pGkxuDlmdVCSEr1y1esjdJcghykR0+HgyzhDCQr+654v4layfDP8ywL9PWIeIfQSXy8P1EVcT3lz32l7byBbWay85NjHPScgXvGXGI+40xe9cTFsP1PgF5u7d4es="
  keep-history: true
  on:
    branch: master
  local-dir: ./build
